platform:ios,'7.0'
pod 'JSONModel', '~> 1.1.2'
pod 'AFNetworking', '~> 2.2.2'
pod 'Masonry', '~> 0.6.3'
pod 'MJRefresh', '~> 3.0.1'
pod 'SDWebImage', '~> 3.7.3'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SuperID', '~> 1.5.0'

#pod 'AMap3DMap'  #3D地图SDK
pod 'AMap2DMap' #2D地图SDK (2D和3D不能同时使⽤用)
pod 'AMapSearch' #搜索服务SDK

pod 'PinYin4Objc', '~> 1.1.1' #汉字转拼音